In [5]:
class bill:
    def __init__(self):
        d={'HDD':5000,'RAM':2000,'printer':6000,'pendrive':800}
        sum=0
        for i,j in d.items():
            n=0
            print(i," - ",j)
            s=input("want this item? (Y/N): ").lower()
            if 'y' in s:
                print("Enter no of ",i,"'s : ",end="")
                n=int(input())
                sum=sum+(j*n)
            elif 'n' in s:
                pass
            else:
                print("Enter valid data!")
            print()
        print("1. cash payment")
        print("1. cheque payment")
        payment=input("Enter method 1/2: ")
        if payment=='1':
            cashpayment(sum)
        else:
            chequepayment(sum)

class cashpayment(bill):
    def __init__(self,amount):
        self.amount=amount
        print("Payment method in cash")
        print("Total amount : ",self.amount)
        n2000=self.amount//2000
        n500=(self.amount%2000)//500
        n200=((self.amount%2000)%500)//200
        n100=(((self.amount%2000)%500)%200)//100
        print("2000 Rs Notes:: ",n2000)
        print("500 Rs Notes:: ",n500)
        print("200 Rs Notes:: ",n200)
        print("100 Rs Notes:: ",n100)
        print("payment successfull!")
        
class chequepayment(bill):
    def __init__(self,amount):
        self.amount=amount
        print("Payment method in cheque")
        print("Total amount : ",self.amount)
        accno=int(input("Enter account no: "))
        chequeno=int(input("Enter cheque no: "))
        print("Payment successfull!")
bill()

HDD  -  5000
want this item? (Y/N): y
Enter no of  HDD 's : 1

RAM  -  2000
want this item? (Y/N): y
Enter no of  RAM 's : 1

printer  -  6000
want this item? (Y/N): y
Enter no of  printer 's : 1

pendrive  -  800
want this item? (Y/N): y
Enter no of  pendrive 's : 1

1. cash payment
1. cheque payment
Enter method 1/2: 1
Payment method in cash
Total amount :  13800
2000 Rs Notes::  6
500 Rs Notes::  3
200 Rs Notes::  1
100 Rs Notes::  1
payment successfull!


# numpy

In [6]:
import numpy as np
import sys

s=range(1000)
print("size of each element of list in bytes: ",sys.getsizeof(s))
print("size of whole list in bytes: ",sys.getsizeof(s)*len(s))

size of each element of list in bytes:  48
size of whole list in bytes:  48000


In [7]:
d=np.arange(1000)
print("size of each element of numpy array in bytes: ",d.itemsize)
print("size of whole element of numpy array in bytes: ",d.itemsize*1000)

size of each element of numpy array in bytes:  4
size of whole element of numpy array in bytes:  4000


In [11]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [13]:
import numpy as np
arr=np.array([[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [24]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [26]:
print(arr[-2,-2,-2])
print(arr[-2,-1,-3])

2
4


In [41]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)


In [34]:
print(arr[1,:3])
print(arr[:1,:3])
print(arr[1:])


[[ 7  8  9]
 [10 11 12]]
[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [10 11 12]]]


In [43]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [44]:
print(arr[0,1:,1:])
print(arr[0:2,0:2,0:2])
print(arr.shape)

[[5 6]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
(2, 2, 3)


In [46]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(type(arr))
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
(1, 1, 1, 1, 5)


In [50]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(2,3)
print(new)
new1=arr.reshape(3,2)
print(new1)
new2=arr.reshape(3,2,1)
print(new2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
