In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,-1)
print(newarr)
print(newarr.base)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### nditer()

In [12]:
# nditer() - to print multi dimensional array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
3


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)

# built-in functions
- 1) concatenate()
- 2) split()
- 3) where
- 4) sort()
- 5) random()

In [20]:
# concatenate()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [25]:
# axis
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
# split()
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [29]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,3)
print(newarr)

[array([1, 2]), array([3]), array([4])]


In [30]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32), array([], dtype=int32)]


In [31]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [32]:
arr1=np.array([[1,2,9,10],[3,4,11,12],[5,6,13,14],[7,8,15,16]])
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([[ 9],
       [11],
       [13],
       [15]]), array([[10],
       [12],
       [14],
       [16]])]


In [36]:
# where
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.where(arr1==4)
print(x)

(array([3, 6], dtype=int64),)


In [37]:
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.where(arr1%2==0)
print(x)

(array([1, 3, 5, 6, 7], dtype=int64),)


In [38]:
arr1=np.array([[1,2],[3,4],[5,6],[4,8]])
x=np.where(arr1==4)
print(x)

(array([1, 3], dtype=int64), array([1, 0], dtype=int64))


In [39]:
arr1=np.array([[[1,2],[3,4]],[[5,4],[4,8]]])
x=np.where(arr1==4)
print(x)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([1, 1, 0], dtype=int64))


In [44]:
#sort()
arr1=np.array([1,2,3,4,5,6,4,8])
print(np.sort(arr1))
arr2=np.array(['apple','cherry','banana','dadam'])
print(np.sort(arr2))
arr3=np.array([True,False,True])
print(np.sort(arr3))

[1 2 3 4 4 5 6 8]
['apple' 'banana' 'cherry' 'dadam']
[False  True  True]


In [52]:
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1))


[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [48]:
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=0))


[[1 2 1]
 [3 4 3]
 [4 7 5]]


In [51]:
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=1))


[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [56]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr1,axis=0))

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]


In [57]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr1,axis=1))

[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


In [125]:
# random module
from numpy import random
x=random.randint(1,4)
print(x)

2


In [126]:
x=random.randint(10,100,size=(5))
print(x)

[46 14 85 50 16]


In [127]:
x=random.randint(10,100,size=(3,5))
print(x)

[[35 56 40 60 31]
 [54 45 18 34 80]
 [71 83 94 90 27]]


In [203]:
x=random.rand(5)
print(x)

[0.88515552 0.21554454 0.86500704 0.06822594 0.67003136]


In [219]:
# 3) random.choice()
x=random.choice([1,3,5,7])
print(x)

3


In [5]:
from numpy import random
b=True
total=0
totalwin=0
while(b):
    ch=input("Enter 1 to play or any other digit to exit : ")
    if ch=='1':
        total+=1
        x=random.randint(101)
        for i in range(7):
            print("attempts left: ",(7-i))
            y=int(input("Your Guess : "))
            if x==y:
                totalwin+=1
                print("your guess is correct!!!")
                print("The no is ",y)
                print()
                break
            else:
                print("Incorrect!")
                if i==6:
                    print("The correct number was ",x)
                if x>y:
                    print("your guess is smaller")
                else:
                    print("your guess is bigger")
                print()
    else:
        b=False
print("you win ",totalwin," out of ",total," games")

Enter 1 to play or any other digit to exit : 1
attempts left:  7
Your Guess : 56
Incorrect!
your guess is bigger

attempts left:  6
Your Guess : 40
Incorrect!
your guess is bigger

attempts left:  5
Your Guess : 25
Incorrect!
your guess is bigger

attempts left:  4
Your Guess : 16
Incorrect!
your guess is bigger

attempts left:  3
Your Guess : 8
Incorrect!
your guess is bigger

attempts left:  2
Your Guess : 3
Incorrect!
your guess is smaller

attempts left:  1
Your Guess : 5
Incorrect!
The correct number was  4
your guess is bigger

Enter 1 to play or any other digit to exit : 1
attempts left:  7
Your Guess : 45
Incorrect!
your guess is smaller

attempts left:  6
Your Guess : 69
Incorrect!
your guess is smaller

attempts left:  5
Your Guess : 80
Incorrect!
your guess is smaller

attempts left:  4
Your Guess : 90
Incorrect!
your guess is bigger

attempts left:  3
Your Guess : 87
your guess is correct!!!
The no is  87

Enter 1 to play or any other digit to exit : 
you win  1  out of  2 